### ISSUE TITLE
Example Meetup Poster

### ISSUE THREAD

**Issue by ridhoassuryadi** [KalselJS/talks#1]
![meetup_poster](https://user-images.githubusercontent.com/16620050/56707480-40414580-6743-11e9-9a84-6ef8ce1022ea.png)

minta tolongb reviewnya @muslih @parinussa @ralfiannor @firdaus1453

**Comment by muslih** [comment]
mintiiip dho :+1:

**Comment by muslih** [comment]
kada bagawi kah imak dho? @muhammadridho  :laughing:

**Comment by ridhoassuryadi** [comment]
begawi, wkwkw

**Comment by ralfiannor** [comment]
Mantap hu @muhammadridho  Meet up offline jg lah ntr di jkt.

**Comment by ridhoassuryadi** [comment]
whahaha, ulun kd sanggup yg newbie ini betamu lwan master master ky (@muslih @firdaus1453 @ralfiannor @parinussa )

**Comment by ridhoassuryadi** [comment]
kalau setuju berikan emoji 👍

**Comment by firdaus1453** [comment]
Pian aja kada sanggup, apalagi olon,  ratik wara 😵

Bagus pang nah betamuan sambil silaturahmi sesama perantauan 🤣
